// generated by "sampctl package init"
#include <a_samp>
#include <a_http>

#define MAIL_URL 		"http://localhost:8080/mail.php"
#define MAIL_ADDRESS	"test@gmail.com"

#include <mail>

main()  {
	// write code here and run "sampctl package build" to compile
	// then run "sampctl package run" to run it
	Mail_Send(0, Mail:MAIL_FUNC, "to_username@gmail.com", "MAIL Name", "Send Mail Test", "Test");
}

Mail_Response:MAIL_FUNC(playerid, response_code, const data[]) {
	switch (response_code) {
        case 200: {
            // success
        }
        default: {
            // error
        }
    }

	printf(data);
}